version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget restore
build:
  project: Skyline.sln
  verbosity: normal
test: off
